# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: midimonster-controller-linux-amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: midimonster-controller
    main: ./cmd/midimonster-controller
    ldflags:
      - -X main.build={{ .Version }}
  - id: midimonster-controller-linux-arm
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "6"
      - "7"
    binary: midimonster-controller
    main: ./cmd/midimonster-controller
    ldflags:
      - -X main.build={{ .Version }}
  - id: midimonster-controller-linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    binary: midimonster-controller
    main: ./cmd/midimonster-controller
    ldflags:
      - -X main.build={{ .Version }}
  - id: midimonster-controller
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
    binary: midimonster-controller
    main: ./cmd/midimonster-controller
    ldflags:
      - -X main.build={{ .Version }}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  use: git
  groups:
    - title: Feat
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fix
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Refactor
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Docs
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999
  filters:
    include:
      - '^.*?feat(\([[:word:]]+\))??!?:.+$'
      - '^.*?bug(\([[:word:]]+\))??!?:.+$'
      - '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      - '^.*?docs(\([[:word:]]+\))??!?:.+$'

release:
  github:
    owner: jduepmeier
    name: midimonster-controller
